eshop/urls.py
from django.conf.urls import url
from . import views

app_name = 'eshop'

urlpatterns = [
    url('^home/$', views.home, name='home'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^register/$', views.UserFormView.as_view(), name = 'register'),
    url(r'^edit/(?P<username>\w+)/$', views.update_profile, name='edit_profile'),
    url('^chekout/$', views.chekout, name='chekout'),

]

pfeproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'', include('eshop.urls', namespace='eshop')),
    url(r'^payments/', include('djstripe.urls', namespace="djstripe")),
    url('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save




class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.FileField(blank=True)
    #cover = models.FileField(blank=True)
    #bio = models.TextField(max_length=500, blank=True)
    #location = models.TextField(max_length=200, blank=True)
    #bd = models.FileField(blank=True, null=True)
    #job = models.FileField(blank=True)

    def get_queryset(self):
        user = User.objects.get(username=self.kwargs['username'])
        return self.model.objects(user=user.id)

    def __str__(self):
        return self.user.username

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile = Profile(user=instance)
        profile.save()

post_save.connect(create_user_profile, sender=User)

eshop/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Profile


class UserForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

        self.fields['password'].required = False
        self.fields['password2'].required = False

    def clean(self):
        super(UserForm, self).clean()
        data = self.cleaned_data
        if data["username"] == True:
            raise forms.ValidationError({'username': ["username already exists"]})
        if data["password"] == "":
            raise forms.ValidationError({'password': ["Password invalid."]})
        elif data["password"] != data["password2"]:
            raise forms.ValidationError({'password': ["Passwords must be the same."]})
        elif len(data["password"]) < 1:
            raise forms.ValidationError({'password': ["password must be at least 6 characters"]})

        if data["email"] == True:
            raise forms.ValidationError({'email': ["email is already in use"]})

        return data

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'placeholder': 'Confirm your password'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                 'placeholder': 'Your password'}))
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your username', }),
        max_length=30,
        required=True)
    email = forms.CharField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Your email'}),
        required=True,
        max_length=75)



    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'password2']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('avatar',)

eshop/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from xmlrpc import client
from django.contrib.auth import authenticate, login
from django_odoo_auth.odoo_auth.models import OdooUser
from django.contrib.auth.models import User
from .forms import UserForm, ProfileForm
from django.views.generic import View
from django.contrib import messages
import base64
import json
from urllib.request import urlopen
import xml.etree.ElementTree as ElementTree


url = 'http://localhost:8069'
db = 'odifydb'
odooname = 'admin'
odoopassword = 'admin'
# returns user objects if credentials are correct
common = client.ServerProxy('{}/xmlrpc/2/common'.format(url))
uid = common.authenticate(db, odooname, odoopassword, {})
models = client.ServerProxy('{}/xmlrpc/2/object'.format(url))

def home(request):
    record = models.execute_kw(db, uid, odoopassword,
                               'product.product', 'search_read', [[['create_uid', '=', 1]]],
                               {'fields': ['id', 'test', 'description', 'image_medium', 'name', 'standard_price']})

    category = models.execute_kw(db, uid, odoopassword,
                                 'product.product', 'search_read', [[['create_uid', '=', 1]]],
                                 {'fields': ['categ_id', 'name', ]})
    x = [x.get('id', ) for x in record]
    # print '____fff__', x
    print ('______username:_______',request.user)
    search_user_id = models.execute_kw(db, uid, odoopassword,
                                       'res.partner', 'search',
                                       [[['name', '=', request.user.username]]])

    print ('______quotation:_______',search_user_id)
    print ('record:_______',record[6]['id'])
    for q in search_user_id:
        if request.method == "POST":
            product = request.POST.get('product')
            print('_________product_____', product)
            is_customer = models.execute_kw(db, uid, odoopassword, 'sale.order',
                                    'search', [[['partner_id', '=', request.user.username]]])
            if not is_customer:
                models.execute_kw(db, uid, odoopassword,
                          'sale.order', 'create', [{'partner_id': q}])
                customer = models.execute_kw(db, uid, odoopassword, 'sale.order',
                                  'search', [[['partner_id', '=', request.user.username]]])
                for order in customer:
                    models.execute_kw(db, uid, odoopassword,
                                  'sale.order', 'write', [[order],
                                                          {'order_line': [(0, 0, {'product_id': int(product)})]}])
            else:

                # order_line =models.execute_kw(db, uid, odoopassword,
                # 		  'sale.order', 'search',
                # 		  [[['partner_id', '=', request.user.username]]])
                for order in is_customer:
                    models.execute_kw(db, uid, odoopassword,
                              'sale.order', 'write', [[order],
                                                      {'order_line': [(0, 0, {'product_id': int(product)})]}])
                #  request.POST.get(record[0]['name'],False)

        return render(request, 'eshop/home.html',
        		  {'product': record[:8], 'category': category, 'product_range': record[12:16], })

class UserFormView(View):

	form_class = UserForm
	template_name = 'eshop/register.html'

	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form': form})

	# process from data

	def post(self, request):
		form = self.form_class(request.POST)

		if form.is_valid():

			user = form.save(commit=False)

			# cleaned data

			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			email = form.cleaned_data['email']
			user.set_password(password)
			user.save()
			user_id = models.execute_kw(db, uid, odoopassword, 'res.partner', 'create',
										[{'name': username, 'login': email}])
			print(user_id)
			user = authenticate(username=username, password=password)
			messages.add_message(request, messages.SUCCESS, 'Your account were successfully created.')

			if user is not None:

				if user.is_active:
					login(request, user)
					#base_template_name = 'base.html'
					return render(request, 'eshop/home.html', {})

		return render(request, self.template_name, {'form': form})


def update_profile(request,username):
	#user = User.objects.get(username=username)
	if request.method == 'POST':
		profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
		if profile_form.is_valid():
			profile_form.save()
			messages.success(request, ('Your profile was successfully updated!'))
			search_user_id = models.execute_kw(db, uid, odoopassword,
											   'res.partner', 'search',
											   [[['name', '=', username]]])
			#print('___', search_user_id)
			img = '/home/imed/Desktop/testpfe/media/'+str(request.user.profile.avatar)
			image_read = image.read()
			image_64_encode = base64.encodestring(image_read).decode("utf-8")
			print('______________',type(image_64_encode))
			for i in search_user_id:
				models.execute_kw(db, uid, odoopassword, 'res.partner', 'write', [[i], {'image': image_64_encode}])
			return redirect('eshop:home')

		else:
			messages.error(request, ('Please correct the error below.'))
	else:
		profile_form = ProfileForm(instance=request.user.profile)
	return render(request, 'eshop/edit_profile.html', {
		'profile_form': profile_form })




def login_user(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)

				return render(request, 'eshop/home.html', {})
			else:
				return render(request, 'eshop/login.html', {'error_message': 'Your account has been disabled'})
		else:
			return render(request, 'eshop/login.html', {'error_message': 'Invalid login'})
	return render(request, 'eshop/login.html')


def chekout(request):
	if request.method == 'POST':
		print (request.method)
	context = {}
	template = 'eshop/chekout.html'
	return render(request,template,context)

eshop/templates/eshop/base.html
<!DOCTYPE html>
{% load staticfiles %}
<!--
    ustora by freshdesignweb.com
    Twitter: https://twitter.com/freshdesignweb
    URL: https://www.freshdesignweb.com/ustora/
-->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ustora Demo</title>

    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="/static/eshop/css/bootstrap.min.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="/static/eshop/css/font-awesome.min.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="/static/eshop/css/owl.carousel.css">
    <link rel="stylesheet" href="{% static 'eshop/css/style.css' %}">
    <link rel="stylesheet" href="/static/eshop/css/responsive.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  <div class="header-area">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="user-menu">
                        <ul>
                            <li><a href="#"><i class="fa fa-user"></i> My Account</a></li>
                            <li><a href="#"><i class="fa fa-heart"></i> Wishlist</a></li>
                            <li><a href="cart.html"><i class="fa fa-user"></i> My Cart</a></li>
                            <li><a href="checkout.html"><i class="fa fa-user"></i> Checkout</a></li>
                            <li><a href="#"><i class="fa fa-user"></i> Login</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="header-right">
                        <ul class="list-unstyled list-inline">
                            <li class="dropdown dropdown-small">
                                <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#"><span class="key">currency :</span><span class="value">USD </span><b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">USD</a></li>
                                    <li><a href="#">INR</a></li>
                                    <li><a href="#">GBP</a></li>
                                </ul>
                            </li>

                            <li class="dropdown dropdown-small">
                                <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#"><span class="key">language :</span><span class="value">English </span><b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">English</a></li>
                                    <li><a href="#">French</a></li>
                                    <li><a href="#">German</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End header area -->

    <div class="site-branding-area">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="logo">
                        <h1><a href="./"><img src="img/logo.png"></a></h1>
                    </div>
                </div>

                <div class="col-sm-6">
                    <div class="shopping-item">
                        <a href="cart.html">Cart - <span class="cart-amunt">$100</span> <i class="fa fa-shopping-cart"></i> <span class="product-count">5</span></a>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End site branding area -->

    <div class="mainmenu-area">
        <div class="container">
            <div class="row">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="index.html">Home</a></li>
                        <li><a href="shop.html">Shop page</a></li>
                        <li><a href="single-product.html">Single product</a></li>
                        <li><a href="cart.html">Cart</a></li>
                        <li><a href="checkout.html">Checkout</a></li>
                        <li><a href="#">Category</a></li>
                        <li><a href="#">Others</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div> <!-- End mainmenu area -->
     {% block body %}
     {% endblock %}


      {% block script %}
      {% endblock %}


    <!-- Latest jQuery form server -->
    <script src="https://code.jquery.com/jquery.min.js"></script>

    <!-- Bootstrap JS form CDN -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    <!-- jQuery sticky menu -->
    <script src="/static/eshop/js/owl.carousel.min.js"></script>
    <script src="/static/eshop/js/jquery.sticky.js"></script>

    <!-- jQuery easing -->
    <script src="/static/eshop/js/jquery.easing.1.3.min.js"></script>

    <!-- Main Script -->
    <script src="/static/eshop/js/main.js"></script>

    <!-- Slider -->
    <script type="text/javascript" src="/static/eshop/js/bxslider.min.js"></script>
    <script type="text/javascript" src="/static/eshop/js/script.slider.js"></script>
  </body>
</html>

eshop/templates/eshop/chekout.html
{% extends 'eshop/base.html' %}

{% block body %}


<div class="container">
    <form action="" method="POST" id="payment-form">
        {% csrf_token %}
    <div class="row">
        <!-- You can make it whatever width you want. I'm making it full width
             on <= small devices and 4/12 page width on >= medium devices -->
        <div class="col-xs-12 col-md-4">


            <!-- CREDIT CARD FORM STARTS HERE -->
            <div class="panel panel-default credit-card-box">
                <div class="panel-heading display-table" >
                    <div class="row display-tr" >
                        <h3 class="panel-title display-td" >Payment Details</h3>
                        <div class="display-td" >
                            <img class="img-responsive pull-right" src="">
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <form role="form" id="payment-form" method="POST" action="javascript:void(0);">
                        <div class="row">
                            <div class="col-xs-12">
                                <div id ="card-element" class="form-group">
                                    <label for="card-element">CARD NUMBER</label>
                                    <div class="input-group">
                                        <input
                                            type="tel"
                                            class="form-control"
                                            name="cardNumber"
                                            placeholder="Valid Card Number"
                                            autocomplete="cc-number"
                                            required autofocus
                                        />
                                        <span class="input-group-addon"><i class="fa fa-credit-card"></i></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--<div class="row">
                            <div class="col-xs-7 col-md-7">
                                <div class="form-group">
                                    <label for="cardExpiry"><span class="hidden-xs">EXPIRATION</span><span class="visible-xs-inline">EXP</span> DATE</label>
                                    <input
                                        type="tel"
                                        class="form-control"
                                        name="cardExpiry"
                                        placeholder="MM / YY"
                                        autocomplete="cc-exp"
                                        required
                                    />
                                </div>
                            </div>
                            <div class="col-xs-5 col-md-5 pull-right">
                                <div class="form-group">
                                    <label for="cardCVC">CV CODE</label>
                                    <input
                                        type="tel"
                                        class="form-control"
                                        name="cardCVC"
                                        placeholder="CVC"
                                        autocomplete="cc-csc"
                                        required
                                    />
                                </div>
                            </div>
                        </div>-->
                        <div class="row">
                            <div class="col-xs-12">
                                <button class="subscribe btn btn-success btn-lg btn-block" type="submit">Start Subscription</button>
                            </div>
                        </div>
                        <div class="row" style="display:none;">
                            <div class="col-xs-12">
                                <p class="payment-errors"></p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!-- CREDIT CARD FORM ENDS HERE -->


        </div>

        <div class="col-xs-12 col-md-8" style="font-size: 12pt; line-height: 2em;">
            <p><h1>Features:</h1>
                <ul>
                    <li>As-you-type, input formatting</li>
                    <li>Form field validation (also as you type)</li>
                    <li>Graceful error feedback for declined card, etc</li>
                    <li>AJAX form submission w/ visual feedback</li>
                    <li>Creates a Stripe credit card token</li>
                </ul>
            </p>
            <p>Be sure to replace the dummy API key with a valid Stripe API key.</p>

            <p>Built upon: Bootstrap, jQuery,
                <a href="http://jqueryvalidation.org/">jQuery Validation Plugin</a>,
                <a href="https://github.com/stripe/jquery.payment">jQuery.payment library</a>,
                and <a href="https://stripe.com/docs/stripe.js">Stripe.js</a>
            </p>
        </div>
    </div>
    </form>
</div>

{% endblock %}

eshop/templates/eshop/edit_profile.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit</title>
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<form enctype="multipart/form-data" method="post" action="">
  {% csrf_token %}

    <button class="btn btn-secondary">{{profile_form.avatar}}<i class="fa fa-upload" aria-hidden="true"></i> </button>

    <div class="form-group ">
        <button type="submit" id="button" class="btn btn-info btn-large login-button">Save changes</button>

    </div>

</form>
</body>
</html>

eshop/templates/eshop/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post"  action="{% url 'eshop:login' %}?next={% url 'eshop:home' %}">
            {% csrf_token %}
            <div class="form-group" style="padding-top:10px;">
              <label class="control-label" for="id_username">Username</label>


              <div class="form1 input-group has-success has-feedback ">
            <span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
              <input class="form-control" type="text" id="name" name="username"
                placeholder="Your usename">
              </div>


            </div>
            <div class="form-group"style="padding-top:15px;">
              <label class="control-label" for="id_password">Password</label>
              <div class="input-group has-success has-feedback">
              <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
              <input class="form-control" type="password" id="id_password" name="password" placeholder="Your password">
              </div>
            </div>
            <div style="padding-top:25px;">
            <button type="submit" id="login"  class="btn btn-success btn-block" style="background:#7cd67c;">Sign in</button><hr>
            Or you can Sing Up <a href="{% url 'eshop:register' %}" class="btn-link" style="color:#24a593;">here</a></div>
          </form>
</body>
</html>

eshop/templates/eshop/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container" >
					<div class="row">
                    <div class="col-md-12 text-center">
                    <h4><img class="" id="fogits" src="/static/img/logo.png" width="120"></h4>
                    </div>
                  </div>
			<div class="row main" style="">
				<div class="panel panel-default col-md-4 col-md-offset-4 main-login main-center"
        style="padding-bottom:15px;">
				<h5 class="pull-left" style="padding-top:35px;">Already have an account ?<a style="color: #24a593;" href="{% url 'eshop:login' %}"> Login Here</a></h5><hr style="width:100%;">

					<form  method="post" role="form" action=""
					 enctype="multipart/form-data">

						{% csrf_token %}

						<div class="form-group ">
						<p><small style='color:#DC143C;'>{{ form.username.errors  }}</small></p>
							<label for="id_username" class="cols-md-2 control-label">Your Username</label>

							<div class="cols-md-10">
								<div class="input-group has-success has-feedback">
									<span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
									{{ form.username }}
								</div>
							</div>
						</div>

						<div class="form-group ">
						<p><small style='color:#DC143C;'>{{ form.email.errors }}</small></p>
							<label for="id_email" class="cols-md-2 control-label">E-mail</label>

							<div class="cols-md-10">
								<div class="input-group has-success has-feedback">
									<span class="input-group-addon"><i class="fa fa-at" aria-hidden="true"></i></span>
									{{ form.email }}
								</div>
							</div>
						</div>
						<div class="form-group ">
							<label for="id_password" class="cols-md-2 control-label">Password</label>
							<div class="cols-md-10">
								<div class="input-group has-success has-feedback">
									<span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
									{{ form.password }}
								</div>
							</div>
						</div>


								<p><small style='color:#DC143C;'>{{ form.password.errors }}</small></p>
						<div class="form-group">
							<label for="id_password2" class="cols-md-2 control-label">Confirm Password
							</label>

							<div class="cols-md-10">
								<div class="input-group has-success has-feedback">
									<span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
									{{ form.password2 }}
								</div>
							</div>
						</div>

						<div class="form-group ">
							<button type="submit" id="register" class="btn btn-success  btn-block login-button" style="background-color:#7cd67c;" >Register</button>
						</div>

					</form>
				</div>
			</div>
		</div>
</body>
</html>